#!/bin/bash
#echo "in ff_stop"
/usr/bin/sudo killall -w ffplay > /dev/null 2>&1
/usr/bin/sudo killall -w pulseaudio > /dev/null 2>&1
#/usr/bin/sudo killall -w -s SIGINT pulseaudio > /dev/null 2>&1
exit 0